import nextVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

const eslintConfig = [
  ...nextVitals,
  ...nextTypescript,
  {
    // `coverage/` is generated by `npm run test:coverage` and gitignored, so CI
    // never sees it — but locally it made `npm run lint` report warnings about
    // Istanbul's own bundled scripts.
    ignores: [".next/**", "out/**", "build/**", "coverage/**", "next-env.d.ts"],
  },
];

export default eslintConfig;
